name: {{ cookiecutter.snap_name }}
version: {{ cookiecutter.openstack_release }}
summary: {{ cookiecutter.project_summary}}
description: |
  {{ cookiecutter.project_description }}
confinement: strict
grade: devel

apps:
  # If the OpenStack service has an API that runs behind uwsgi+nginx, the folowing
  # app is required.
  uwsgi:
    command: snap-openstack {{ cookiecutter.snap_name }}-uwsgi
    daemon: simple
    plugs:
      - network-bind
  # If the OpenStack service has an API that runs behind uwsgi+nginx, the folowing
  # app is required.
  nginx:
    command: snap-openstack {{ cookiecutter.snap_name }}-nginx
    daemon: forking
    plugs:
      - browser-support
      - network-bind
  # Following is an example of creating a command app. Aliases should be defined to enable
  # well-known command names.
  manage:
    command: snap-openstack {{ cookiecutter.snap_name }}-manage
    aliases:
      - {{ cookiecutter.snap_name }}-manage
    plugs:
      - network

parts:
  # Following is an example of defining a part to build an OpenStack project
  {{ cookiecutter.snap_name }}:
    plugin: python
    python-version: python2
    source: http://tarballs.openstack.org/{{ cookiecutter.snap_name }}/{{ cookiecutter.snap_name }}-stable-{{ cookiecutter.openstack_release }}.tar.gz
    python-packages:
      # You'll likely need to pull in additional python packages
      - git+https://github.com/openstack/snap.openstack#egg=snap.openstack
    constraints: https://raw.githubusercontent.com/openstack/requirements/stable/{{ cookiecutter.openstack_release }}/upper-constraints.txt
    build-packages:
      - gcc
      - libffi-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
    install:
      touch $SNAPCRAFT_PART_INSTALL/lib/python2.7/site-packages/paste/__init__.py
      touch $SNAPCRAFT_PART_INSTALL/lib/python2.7/site-packages/repoze/__init__.py
      export SNAP_ROOT="../../../"
      export SNAP_SITE_PACKAGES="$SNAPCRAFT_PART_INSTALL/lib/python2.7/site-packages"
      patch -d $SNAP_SITE_PACKAGES -p1 < $SNAP_ROOT/patches/oslo-config-dirs.patch
  templates:
    after: [{{ cookiecutter.snap_name }}]
    plugin: dump
    source: snap
  # Following is an example of including the OpenStack project's config
  config:
    after: [{{ cookiecutter.snap_name }}]
    plugin: dump
    source: http://tarballs.openstack.org/{{ cookiecutter.snap_name }}/{{ cookiecutter.snap_name }}-stable-{{ cookiecutter.openstack_release }}.tar.gz
    organize:
      etc/*.conf: etc/{{ cookiecutter.snap_name }}/
      etc/*.ini: etc/{{ cookiecutter.snap_name }}/
      etc/*.json: etc/{{ cookiecutter.snap_name }}/
      etc/*.templates: etc/{{ cookiecutter.snap_name }}/
    filesets:
      etc:
        - etc/{{ cookiecutter.snap_name }}/*.conf
        - etc/{{ cookiecutter.snap_name }}/*.ini
        - etc/{{ cookiecutter.snap_name }}/*.json
        - etc/{{ cookiecutter.snap_name }}/*.templates
    stage: [$etc]
    prime: [$etc]
  # If the OpenStack service has an API that runs behind uwsgi+nginx, the following
  # part is required.
  nginx:
    source: http://www.nginx.org/download/nginx-1.13.0.tar.gz
    plugin: autotools
    configflags:
      - --prefix=/usr
      - --http-log-path=/var/snap/{{ cookiecutter.snap_name }}/common/log/nginx-access.log
      - --error-log-path=/var/snap/{{ cookiecutter.snap_name }}/common/log/nginx-error.log
      - --lock-path=/var/snap/{{ cookiecutter.snap_name }}/common/lock/nginx.lock
      - --pid-path=/var/snap/{{ cookiecutter.snap_name }}/common/run/nginx.pid
      - --http-client-body-temp-path=/var/snap/{{ cookiecutter.snap_name }}/common/lib/nginx_client_body
      - --http-proxy-temp-path=/var/snap/{{ cookiecutter.snap_name }}/common/lib/nginx_proxy
      - --http-fastcgi-temp-path=/var/snap/{{ cookiecutter.snap_name }}/common/lib/nginx_fastcgi
      - --http-uwsgi-temp-path=/var/snap/{{ cookiecutter.snap_name }}/common/lib/nginx_uwsgi
      - --http-scgi-temp-path=/var/snap/{{ cookiecutter.snap_name }}/common/lib/nginx_scgi
    build-packages:
      - libpcre3-dev
      - libssl-dev
    prepare: |
      export SNAP_ROOT="../../.."
      export SNAP_SOURCE="$SNAP_ROOT/parts/nginx/build"
      patch -d $SNAP_SOURCE -p1 < $SNAP_ROOT/patches/drop-nginx-setgroups.patch
